#ifndef INCLUDED_HULANG_TOKEN_TYPE_DEF_H
#define INCLUDED_HULANG_TOKEN_TYPE_DEF_H

#ifdef __cplusplus
extern "C" {
#endif

#define HULANG_TOKEN_TYPE_ID 0
#define HULANG_TOKEN_TYPE_INTEGER 1
#define HULANG_TOKEN_TYPE_FLOAT 2
#define HULANG_TOKEN_TYPE_STRING 3
#define HULANG_TOKEN_TYPE_QMARK 4
#define HULANG_TOKEN_TYPE_COLON 5
#define HULANG_TOKEN_TYPE_ASSIGN 6
#define HULANG_TOKEN_TYPE_PLUS_ASSIGN 7
#define HULANG_TOKEN_TYPE_MINUS_ASSIGN 8
#define HULANG_TOKEN_TYPE_MULTIPLY_ASSIGN 9
#define HULANG_TOKEN_TYPE_DIVIDE_ASSIGN 10
#define HULANG_TOKEN_TYPE_MOD_ASSIGN 11
#define HULANG_TOKEN_TYPE_INC 12
#define HULANG_TOKEN_TYPE_DEC 13
#define HULANG_TOKEN_TYPE_OR 14
#define HULANG_TOKEN_TYPE_AND 15
#define HULANG_TOKEN_TYPE_LT 16
#define HULANG_TOKEN_TYPE_GT 17
#define HULANG_TOKEN_TYPE_LE 18
#define HULANG_TOKEN_TYPE_GE 19
#define HULANG_TOKEN_TYPE_EQ 20
#define HULANG_TOKEN_TYPE_NE 21
#define HULANG_TOKEN_TYPE_NOT 22
#define HULANG_TOKEN_TYPE_PLUS 23
#define HULANG_TOKEN_TYPE_MINUS 24
#define HULANG_TOKEN_TYPE_MULTIPLY 25
#define HULANG_TOKEN_TYPE_DIVIDE 26
#define HULANG_TOKEN_TYPE_MOD 27
#define HULANG_TOKEN_TYPE_POWER 28
#define HULANG_TOKEN_TYPE_LPAR 29
#define HULANG_TOKEN_TYPE_RPAR 30
#define HULANG_TOKEN_TYPE_EOS 31
#define HULANG_TOKEN_TYPE_ERROR 32

#ifdef __cplusplus
} // end extern "C"
#endif
    
#endif // INCLUDED_HULANG_TOKEN_TYPE_DEF_H
